---
title: "Untitled"
author: "Sigert"
date: "5 June 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
list.of.packages <- c("knitr","rjags","runjags", "haven","psych","car","magicfor","lattice", "kableExtra")
new.packages <- list.of.packages[!(list.of.packages %in%installed.packages()[,"Package"])]
if(length(new.packages)){install.packages(new.packages,repos = "http://cran.us.r-project.org")}
lapply(list.of.packages, require, character.only = TRUE)

set.seed(777)
Mywd<- getwd()
setwd(Mywd)
```

```{r datapreparation, include=FALSE}
## Unique ID's
my.normalize <- function(x) {
  return ((x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE)))
  }

set.seed(777)
# rm(list=ls())

data.raw <- read.csv("soep_statV.csv", header = TRUE, sep = ",", dec = ".")
data.raw.tmp <- transform(data.raw, pp=match(id,unique(id)))
data.recoded <- data.raw.tmp
data.recoded$emplStat55[data.raw.tmp$emplStat55!=1] <- 0

norm.pp <- data.recoded$pp
norm.LS <- my.normalize(data.recoded$lifeSat) # ls: life satisfaction
norm.Age <- my.normalize(data.recoded$age) #  age
norm.Empl <- my.normalize(data.recoded$emplStat55) # e: is he full-time employed?
norm.Health <- my.normalize(data.recoded$healthSat) #  h: health
norm.Partner <- my.normalize(data.recoded$livtog) # p: partneered?

data.norm <- as.data.frame(cbind(norm.pp,norm.Empl,norm.Age,norm.Health,norm.Partner,norm.LS))

save(data.norm, file = "data.norm.Rdata")

Nsubjects <- length(unique(data.norm[,1]))
Ntotal <- length(data.norm[,1])

yName = "norm.LS" 
xName = c("norm.Empl","norm.Age", "norm.Health", "norm.Partner")
y = data.norm[6]
x = as.matrix(data.norm[2:5],ncol=length(xName))

Empl = x[,1]
Age = x[,2] 
Health = x[,3]
Partner = x[,4]


```

```{r Jags preparation, include=FALSE}

dataList = list(
    x = x ,
    y = y ,
    s = norm.pp ,
    Ntotal = Ntotal ,
    Nx = dim(x)[4] ,
    NxO = dim(x)[4]-1, #employment is measured at the individual level
    Nsubjects = Nsubjects 
  )

```



```{r JAGS specifics}
nchains = 2
nadapt = 200 #many uninformative dispersion parameters
nburn = 500
niter = 3000
myinits <- NULL
```


```{r Exploratory Statistics}
# Life satisfaction by age

mean.table1=tapply(clean.data$ls,list(clean.data$age, clean.data$partner),mean)
mean.table3=tapply(clean.data$ls,list(clean.data$age, clean.data$employ),mean)
mean.table4=tapply(clean.data$ls,list(clean.data$age, clean.data$health),mean)

# life satisfaction as a function of Living together and age
colors=c("black","red")
plot(unique(clean.data$age),mean.table1[,1],type="b",xlim=c(0,5),ylim=c(0,10),xlab="Age (in years)",ylab="Life Satisfaction",axes=F,main="Life satisfaction as a function of Living together and age")
axis(side=1,at=c(0,1,2,3,4,5),labels=c(55,56,57,58,59,60))
axis(side=2,at=seq(0,10,1))
box()
points(unique(clean.data$age),mean.table1[,2],type="b",col="red")
# life satisfaction as a function of employement and age

colors=c("black","red")
plot(unique(clean.data$age),mean.table3[,1],type="b",xlim=c(0,5),ylim=c(0,10),xlab="Age (in years)",ylab="Life Satisfaction",axes=F,main="Life satisfaction as a function of employement and age")
axis(side=1,at=c(0,1,2,3,4,5),labels=c(55,56,57,58,59,60))
axis(side=2,at=seq(0,10,1))
box()
points(unique(clean.data$age),mean.table3[,2],type="b",col="red")
# life satisfaction as a function of health status and age

par(xpd=TRUE)
colors=rainbow(10)
plot(unique(clean.data$age),mean.table4[,1],type="n",xlim=c(0,5),ylim=c(0,10),xlab="Age (in years)",ylab="Life satisfaction",axes=F,main="life satisfaction as a function of health status and age")
axis(side=1,at=c(0,1,2,3,4,5),labels=c(55,56,57,58,59,60))
axis(side=2,at=seq(0,10,1))
box()
for(i in 1:length(colors)){
  points(unique(clean.data$age),mean.table4[,1+i],type="b",col=colors[i])
  legend(-0.180, 2, x.intersp = 0.12, legend = colnames(mean.table4), fill = colors, horiz=TRUE)
}

```

```{r model without interactions: model}
modelString = "
model {
for ( i in 1:Ntotal ) {
	y[i] ~ dnorm( beta0[pp[i]] + beta1[pp[i]]*x[i,1]+ beta2[pp[i]]*x[i, 2]+beta3[pp[i]]*x[i,3]+beta4[pp[i]]*x[i,4] + sum( beta[1:NxO] * x[i,2:Nx] ), 1/sigma^2 )
} 
#Empl Age Health Partner
for (j in 1:Nsubjects){
  beta0[j] ~ dnorm( beta0mu , 1/(beta0sigma)^2 ) 
  beta1[j] ~ dnorm( beta1mu , 1/(beta1sigma)^2 )
  beta2[j] ~ dnorm( beta2mu , 1/(beta2sigma)^2 )
  beta3[j] ~ dnorm( beta3mu , 1/(beta3sigma)^2 )
  beta4[j] ~ dnorm( beta4mu , 1/(beta4sigma)^2 )
}	
 # Priors vague :
    for ( k in 1:length(NxO )) {
      beta[k] ~ dnorm( 0 , 1/2^10 )
    }

    beta0mu ~ dnorm( 0 , 1/(10)^3 ) 
    beta1mu ~ dnorm( 0 , 1/(10)^3 )
    beta0sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
    beta1sigma ~ dunif( 1.0E-3 , 1.0E+3 )
    beta2mu ~ dnorm( 0 , 1/(10)^3 ) 
    beta3mu ~ dnorm( 0 , 1/(10)^3 )
    beta2sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
    beta3sigma ~ dunif( 1.0E-3 , 1.0E+3 )
    beta4mu ~ dnorm( 0 , 1/(10)^3 ) 
    beta4sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
    sigma ~ dunif( 1.0E-3 , 1.0E+3 )
}
"

writeLines(modelString , con="model_full_no_correlation" )
```

```{r model without interactions:, Jags Cache = T}
#no correlation, using standardized data for life satisfaction and health variables

xvars <- as.matrix(data.norm, ncols = length(colnames(data.norm)))
xvarss <- xvars[,2:5]
Beta <- c(0:5)

y = data.norm[, 6]
pp = data.norm[, 1]

simple_model <- list(
  y = y,
  pp = pp,
  x = x,
  Nx = ncol(x) ,
  NxO = ncol(x)-1,
  Nsubjects = Nsubjects,
  beta = Beta,
  Ntotal = Ntotal
)

out.simple.model <- run.jags(model = "model_full_no_correlation", monitor = c("beta0mu", "beta1mu", "beta2mu","beta3mu","beta4mu", "beta"), data = simple_model, inits = myinits, n.chains = nchains, adapt = nadapt, burnin = nburn, sample = niter)

save(out.simple.model, file = "simple.model.Rdata")

```


# large beta for age, because of other confounds? 
#Model looking at interactions

```{r model with interactions: model}
modelString = "
model {
for ( i in 1:Ntotal ) {
	y[i] ~ dnorm( beta0[pp[i]] + beta1[pp[i]]*x[i,1]+ beta2[pp[i]]*x[i, 2]+beta3[pp[i]]*x[i,3]+beta4[pp[i]]*x[i,4] +  beta[1] * x[i,2], 1/sigma^2 )
} 
#Empl Age Health Partner
for (j in 1:Nsubjects){
  beta0[j] ~ dnorm( beta0mu , 1/(beta0sigma)^2 ) 
  beta1[j] ~ dnorm( beta1mu , 1/(beta1sigma)^2 )
  beta2[j] ~ dnorm( beta2mu , 1/(beta2sigma)^2 )
  beta3[j] ~ dnorm( beta3mu , 1/(beta3sigma)^2 )
  beta4[j] ~ dnorm( beta4mu , 1/(beta4sigma)^2 )
}	
 # Priors vague :

    beta[1] ~ dnorm( 0 , 1/2^10 )

    beta0mu ~ dnorm( 0 , 1/(10)^3 ) 
    beta1mu ~ dnorm( 0 , 1/(10)^3 )
    beta0sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
    beta1sigma ~ dunif( 1.0E-3 , 1.0E+3 )
    beta2mu ~ dnorm( 0 , 1/(10)^3 ) 
    beta3mu ~ dnorm( 0 , 1/(10)^3 )
    beta2sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
    beta3sigma ~ dunif( 1.0E-3 , 1.0E+3 )
    beta4mu ~ dnorm( 0 , 1/(10)^3 ) 
    beta4sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
    sigma ~ dunif( 1.0E-3 , 1.0E+3 )
}
"

writeLines(modelString , con="model_full_interaction" )
```



