---
title: "Untitled"
author: "Sigert"
date: "5 June 2018"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
list.of.packages <- c("knitr","rjags","runjags", "haven","psych","car","magicfor","lattice")
new.packages <- list.of.packages[!(list.of.packages %in%installed.packages()[,"Package"])]
if(length(new.packages)){install.packages(new.packages,repos = "http://cran.us.r-project.org")}
lapply(list.of.packages, require, character.only = TRUE)

set.seed(777)
Mywd<- getwd()
setwd(Mywd)
```

```{r datapreparation, include=FALSE}
## Unique ID's
my.normalize <- function(x) {
  return ((x - mean(x, na.rm = TRUE)) / (sd(x, na.rm = TRUE)))
  }

set.seed(777)
#rm(list=ls())

data.raw <- read.csv("soep_statV.csv", header = TRUE, sep = ",", dec = ".")
data.raw.tmp <- transform(data.raw, pp=match(id,unique(id)))
data.recoded <- data.raw.tmp
data.recoded$emplStat55[data.raw.tmp$emplStat55!=1] <- 0

pp <- data.recoded$pp
norm.ls <- my.normalize(data.recoded$lifeSat) # ls: life satisfaction
norm.a <- my.normalize(data.recoded$age-55) #  age
norm.e <- data.recoded$emplStat55 # e: is he full-time employed?
norm.h <- my.normalize(data.recoded$healthSat) #  h: health
norm.p <- data.recoded$livtog # p: partneered?

data.norm <- as.data.frame(cbind(pp,norm.ls,norm.a,norm.h,norm.p,norm.e))
hist(data.raw$healthSat)
mean(data.raw$healthSat)
save(data.norm, file = "data.norm.Rdata")


Nsubjects <- length(unique(data.norm[,1]))
Ntotal <- length(data.norm[,1])

yName = "norm.LS" 
xName = c("norm.Age", "norm.Health", "norm.Partner","norm.Empl")
y1 <- data.norm[2]
y <- as.matrix(y1)
x = as.matrix(data.norm[3:6],ncol=length(xName))

Empl = x[,4]
Age = x[,1] 
Health = x[,2]
Partner = x[,3]
pp = unique(Age)

AgeXHealth = data.norm[, "norm.a"]*data.norm[, "norm.h"]
AgeXPartner = data.norm[, "norm.a"]*data.norm[, "norm.p"]
AgeXEmploy = data.norm[, "norm.a"]*data.norm[, "norm.e"]
HealthXEmploy = data.norm[, "norm.h"]*data.norm[, "norm.e"]
AgeXHealthXEmploy = data.norm[,"norm.a"]*data.norm[,"norm.h"]*data.norm[,"norm.h"]

```

```{r exploratory plots}
clean.data <- transform(data.raw, pp=match(id,unique(id)))

##centering
clean.data$age <-data.raw$age-55

##recoding some variables
clean.data$emplStat55[clean.data$emplStat55 == 2] <- 0
clean.data$emplStat55[clean.data$emplStat55 == 3] <- 0

variable.names <- list("id","ls", "age", "employ","health","partner","pp")
colnames(clean.data) <- variable.names


mean.table1=tapply(clean.data$ls,list(clean.data$age, clean.data$partner),mean)
mean.table3=tapply(clean.data$ls,list(clean.data$age, clean.data$employ),mean)
mean.table4=tapply(clean.data$ls,list(clean.data$age, clean.data$health),mean)

# life satisfaction as a function of Living together and age
colors=c("black","red")
plot(unique(clean.data$age),mean.table1[,1],type="b",xlim=c(0,5),ylim=c(0,10),xlab="Age (in years)",ylab="Life Satisfaction",axes=F,main="Life satisfaction as a function of Living together and age")
axis(side=1,at=c(0,1,2,3,4,5),labels=c(55,56,57,58,59,60))
axis(side=2,at=seq(0,10,1))
box()
points(unique(clean.data$age),mean.table1[,2],type="b",col="red")
# life satisfaction as a function of employement and age

colors=c("black","red")
plot(unique(clean.data$age),mean.table3[,1],type="b",xlim=c(0,5),ylim=c(0,10),xlab="Age (in years)",ylab="Life Satisfaction",axes=F,main="Life satisfaction as a function of employement and age")
axis(side=1,at=c(0,1,2,3,4,5),labels=c(55,56,57,58,59,60))
axis(side=2,at=seq(0,10,1))
box()
points(unique(clean.data$age),mean.table3[,2],type="b",col="red")
# life satisfaction as a function of health status and age

par(xpd=TRUE)
colors=rainbow(10)
plot(unique(clean.data$age),mean.table4[,1],type="n",xlim=c(0,5),ylim=c(0,10),xlab="Age (in years)",ylab="Life satisfaction",axes=F,main="life satisfaction as a function of health status and age")
axis(side=1,at=c(0,1,2,3,4,5),labels=c(55,56,57,58,59,60))
axis(side=2,at=seq(0,10,1))
box()
for(i in 1:length(colors)){
  points(unique(clean.data$age),mean.table4[,1+i],type="b",col=colors[i])
  legend(-0.180, 2, x.intersp = 0.12, legend = colnames(mean.table4), fill = colors, horiz=TRUE)
}
```

```{r JAGS specifics}
nchains = 2
nadapt = 1000 #many uninformative dispersion parameters
nburn = 1000
niter = 2000
myinits <- NULL
```


```{r Model with correlations and relevant}
#Preperation

x = as.matrix(data.norm[3:6],ncol=length(xName))
x = cbind(x, AgeXHealth, AgeXPartner, AgeXEmploy, HealthXEmploy)


Nx = dim(x)[2]
Nx0 = dim(x)[2]-3 #Change for between subject madness

dataList.I.COR = list(
    x = x ,
    y = y ,
    pp = pp ,
    Ntotal = Ntotal ,
    Nsubjects = Nsubjects,
    Nx0 = Nx0,
    Nx= Nx,
    omega = diag(c(1,1,1)),
    mean = c(0,0,0),
    df = 3+1,
    prec = diag(c(1.0E-6,1.0E-6,1.0E-6))
  )
```


```{r Models With all Correlation and relevant interactions}
modelString = "
model {
for ( i in 1:Ntotal ) {
	y[i,1] ~ dnorm( beta[pp[i],1] + beta[pp[i],2]*x[i, 2]+beta[pp[i],3]*x[i,3]+ sum( betax[1:Nx0] * x[i,(Nx-Nx0+1):Nx]), 1/sigma^2 )
} 
 # Don't forget to set your between subjects to the end of X! Dont forget that the first beta is beta0

#Betas
for(j in 1:Nsubjects){
beta[j, 1:3] ~ dmnorm( betamu , M ) 
}
 #Priors vague:
for (q in 1:Nx0){
  betax[q] ~ dnorm( 0 , 1/(10)^5)
}

  betamu[1:3] ~ dmnorm(mean, prec)

  M[1 : 3, 1 : 3] ~ dwish(omega, df)
  MA <- inverse(M)
  
  for (z in 1:3){ #variance to sd
  ss[z] <- sqrt(MA[z,z])
  }
  cor12 <- MA[1,2]/ss[1]*ss[2]
  cor13 <- MA[1,3]/ss[1]*ss[3]
  cor23 <- MA[2,3]/ss[2]*ss[3]

  sigma ~ dunif( 1.0E-3 , 1.0E+3 )  

}
"

writeLines(modelString , con="model_full_correlation" )
```


```{r Running Jags correlation}
parameters.C.I <- c("ss", "cor12","cor13","cor23","betamu", "betax")

out.model.COR <- run.jags(model = "model_full_correlation", monitor = parameters.C.I, data = dataList.I.COR, inits = myinits, n.chains = nchains, adapt = nadapt, burnin = nburn, sample = niter, thin = 180)

summary(out.model.COR)
save(out.model.COR,file = "out.model.COR.thin.rdata")
```

```{r Model with refined correlations and interactions}
#Preperation

x = as.matrix(data.norm[3:6],ncol=length(xName))
x = cbind(x, AgeXHealthXEmploy)


Nx = dim(x)[2]
Nx0 = dim(x)[2]-3 #Change for between subject madness
meana <- runif(1, min=-10, max=10)
meanb <- runif(1, min=-10, max=10)

dataList.I.COR2 = list(
    x = x ,
    y = y ,
    pp = pp ,
    Ntotal = Ntotal ,
    Nsubjects = Nsubjects,
    Nx0 = Nx0,
    Nx= Nx,
    omega = diag(c(1,1)),
    mean = c(0,0),
    df = 2+1,
    prec = diag(c(1.0E-6,1.0E-6))
  )
```

```{r Models With refined Correlation and refined interactions}
modelString = "
model {
for ( i in 1:Ntotal ) {
	y[i,1] ~ dnorm( beta[pp[i],1] + beta[pp[i],2]*x[i, 3]+beta2[pp[i]]*x[i,2]+ sum( betax[1:Nx0] * x[i,(Nx-Nx0+1):Nx]), 1/sigma^2 )
} 
 # Don't forget to set your between subjects to the end of X! Dont forget that the first beta is beta0

#Betas
for(j in 1:Nsubjects){
beta[j, 1:2] ~ dmnorm( betamu , M )
beta2[j] ~ dnorm( betamu2 , 1/(10)^5)
}
 #Priors vague:
for (q in 1:Nx0){
  betax[q] ~ dnorm( 0 , 1/(10)^5)
}

  betamu[1:2] ~ dmnorm(mean, prec)
  betamu2 ~ dnorm(0, 1/(10)^5)

  M[1 : 2, 1 : 2] ~ dwish(omega, df)
  MA <- inverse(M)
  
  for (z in 1:2){ #variance to sd
  ss[z] <- sqrt(MA[z,z])
  }
  cor12 <- MA[1,2]/ss[1]*ss[2]

  sigma ~ dunif( 1.0E-3 , 1.0E+3 )  
Empl = x[,4]
Age = x[,1] 
Health = x[,2]
Partner = x[,3]
}
"

writeLines(modelString , con="model_full_correlation_2" )
```

```{r Running Jags correlation final}
parameters.C.I.2 <- c("ss", "cor12","betamu", "betax")

out.model.COR2 <- run.jags(model = "model_full_correlation_2", monitor = parameters.C.I.2, data = dataList.I.COR2, inits = myinits, n.chains = nchains, adapt = nadapt, burnin = nburn, sample = niter, thin = 1)

summary(out.model.COR2)

```

```{r Models With refined Correlation and refined interactions}
modelString.sens = "
model {
for ( i in 1:Ntotal ) {
	y[i,1] ~ dnorm( beta[pp[i],1] + beta[pp[i],2]*x[i, 3]+beta2[pp[i]]*x[i,2]+ sum( betax[1:Nx0] * x[i,(Nx-Nx0+1):Nx]), 1/sigma^2 )
} 
 # Don't forget to set your between subjects to the end of X! Dont forget that the first beta is beta0

#Betas
for(j in 1:Nsubjects){
beta[j, 1:2] ~ dmnorm( betamu , M )
beta2[j] ~ dnorm( betamu2 , 1/(10)^2)
}
 #Priors vague:
for (q in 1:Nx0){
  betax[q] ~ dnorm( rand , 1/(10)^2)
}

rand ~ dunif(-10, 10)
rand2 ~ dunif(-10, 10) 
  betamu[1:2] ~ dmnorm(mean, prec)
  betamu2 ~ dnorm(rand2, 1/(10)^2)

  M[1 : 2, 1 : 2] ~ dwish(omega, df)
  MA <- inverse(M)
  
  for (z in 1:2){ #variance to sd
  ss[z] <- sqrt(MA[z,z])
  }
  cor12 <- MA[1,2]/ss[1]*ss[2]

  sigma ~ dunif( 1.0E-1 , 1.0E+1 )  

}
"

writeLines(modelString.sens , con="model_full_correlation_2.sens" )
```

```{r sens two thin jags}

timer1.s <- tictoc::tic()
parameters.C.I <- c("ss", "cor12","cor13","cor23","betamu", "betax","sigma")

out.model.COR <- run.jags(model = "model_full_correlation", monitor = parameters.C.I, data = dataList.I.COR, inits = myinits, n.chains = nchains, adapt = nadapt, burnin = nburn, sample = 1000, thin = 150)
timer1.e <- tictoc::toc()
out.model.COR.sen <- out.model.COR
sum.sens.1 <- summary(out.model.COR)
save(out.model.COR.sen,file = "out.model.COR.sen.thin.rdata")


timer2.s <- tictoc::tic()
parameters.C.I.2.sens <- c("ss", "cor12","betamu", "betax", "sigma")

out.model.COR2.sens <- run.jags(model = "model_full_correlation_2.sens", monitor = parameters.C.I.2.sens, data = dataList.I.COR2.sens, inits = myinits, n.chains = nchains, adapt = nadapt, burnin = nburn, sample = 800, thin = 300)

timer2.e <- tictoc::toc()

sum.sens.2 <- summary(out.model.COR2)
save(out.model.COR2.sens,file = "out.model.COR2.sens.thick.rdata")

```


